name: Build, Test, Package, and Publish

on: workflow_dispatch

jobs:
    build-test-package-publish:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0 # Avoid shallow clone which breaks Nerdbank.GitVersioning.
        
        - uses: actions/setup-dotnet@v3
          with:
              dotnet-version: 8.0.x
              
        - run: dotnet restore
          
        - run: dotnet build --no-restore --configuration Release
          
        - run: dotnet test --no-build --configuration Release --verbosity normal
  
        - run: dotnet pack --no-build --configuration Release NorthSouthSystems.Text\NorthSouthSystems.Text.csproj
  
        - run: dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_APIKEY}} "NorthSouthSystems.Text\bin\Release\*.nupkg"